import { ResearchOpportunity } from './types';

// Data parsed directly from the CSV provided in the prompt
export const RESEARCH_DATA: ResearchOpportunity[] = [
  {
    id: "kornu-2025",
    piLastName: "Kornu",
    piFirstName: "Kimbell",
    email: "kimbell.kornu@belmont.edu",
    title: "Professor (or Clinical Professor)",
    degree: "MD/PhD",
    department: "Foundational and Clinical Sciences",
    researchFocus: "Bioethics, Palliative Care, Clinical Ethics",
    keywords: "Religion, Theology, Bioethics, End of Life Care, Philosophy",
    programDescription: "I investigate philosophical, social, theological, and historical determinants that shape the practice of modern medicine, engaging in questions of mortality, technology, religion, spirituality, ways of knowing, philosophical anthropology, and clinical ethics.",
    projectOverview: "(1) Investigating the nature of AI as a mirror of how we conceptualize human intelligence and how that affects our understanding of what it means to be human both inside and outside of medicine. (2) Investigating principles from philosophy, theology, history, and the visual arts to consider the proper way to \"see\" a patient as a whole person.",
    studentCount: "10",
    timeframe: ["Summer Research Elective", "Academic Year (Ongoing)"],
    startTerm: ""
  },
  {
    id: "lowe-2025",
    piLastName: "Lowe",
    piFirstName: "Robert",
    email: "lowerw@toa.com",
    title: "MD TOA community faculty",
    degree: "MD",
    department: "Orthopedic",
    researchFocus: "Clinical research, Orthopaedic Surgery",
    keywords: "Spine, Clinical outcome research and possible cell biology",
    programDescription: "New faculty. Foster their own leaning style.",
    projectOverview: "Review of spine surgery outcomes. Help review and collect data.",
    studentCount: "1-2",
    timeframe: ["Summer Research Elective", "Academic Year (Ongoing)"],
    startTerm: ""
  },
  {
    id: "whitworth-2025",
    piLastName: "Whitworth",
    piFirstName: "Pat",
    email: "pat.whitworth@belmont.edu",
    title: "Assistant Professor",
    degree: "MD",
    department: "Clinical and/or Educational Research",
    researchFocus: "Basic science; Diagnostic Radiology; Interventional Radiology",
    keywords: "Radiology, Diagnostic Radiology, Interventional Radiology, AI, Artificial Intelligence",
    programDescription: "Current projects include radiology case reports, classic imaging signs, literature reviews, and research in the scholarship of teaching and learning including curriculum development.",
    projectOverview: "AMSER Case of the Month submissions; Classics in Abdominal Radiology (peer-reviewed); Literature reviews; Scholarship of teaching and learning (Radiology/POCUS curriculum development).",
    studentCount: "3",
    timeframe: ["Summer Research Elective", "Academic Year (Ongoing)"],
    startTerm: "Spring 2026"
  },
  {
    id: "ryan-b-1",
    piLastName: "Ryan",
    piFirstName: "Benjamin",
    email: "ben.ryan@belmont.edu",
    title: "Professor",
    degree: "PhD",
    department: "Health Systems Science",
    researchFocus: "Public health, Family Medicine",
    keywords: "Public health; environmental health science; disaster risk reduction; sanitation; community resilience; systems thinking; policy",
    programDescription: "I prioritize collaborative learning, real-world application, and interdisciplinary engagement. My mentoring style is supportive, adaptive, and goal-oriented.",
    projectOverview: "High tech/low tech medicine equity; The forgotten field of sanitation in medical curriculum; The dimensions of physician neutrality in conflict; Managing vaccination reluctance; Disaster detection/alerts; Disaster resilience standards.",
    studentCount: "10",
    timeframe: ["Academic Year (Ongoing)"],
    startTerm: "Spring 2026"
  },
  {
    id: "ryan-b-2",
    piLastName: "Ryan",
    piFirstName: "Benjamin",
    email: "ben.ryan@belmont.edu",
    title: "Professor",
    degree: "PhD",
    department: "Health Systems Science",
    researchFocus: "Public health, Diagnostic Radiology; Family Medicine; OBGYN",
    keywords: "C-section; ultrasound; pre-natal; Burundi",
    programDescription: "Focus on global health and humanitarian service leadership.",
    projectOverview: "Zigama-Mama: Evaluating benefit of free ultrasounds to pregnant women with C-section history in Burundi; Comparison of complication rates between urgent and scheduled repeat C-sections in Burundi; Heat wave preparedness in Turkey hospitals.",
    studentCount: "4",
    timeframe: ["Academic Year (Ongoing)"],
    startTerm: "Fall 2025"
  },
  {
    id: "thurman-2025",
    piLastName: "Thurman",
    piFirstName: "Kendall",
    email: "kendall.thurman@belmont.edu",
    title: "Assistant Professor",
    degree: "DO",
    department: "Foundational and Clinical Sciences",
    researchFocus: "Clinical research, Emergency Medicine; Family Medicine",
    keywords: "Doctor-Patient communication",
    programDescription: "How faculty perspective on students affects student mindset.",
    projectOverview: "A study on how faculty perspective on students affects student mindset. Does the outlook on students (deficit or asset-based) affect students' growth mindset? Surveys will be provided to faculty.",
    studentCount: "2-4",
    timeframe: ["Academic Year (Ongoing)"],
    startTerm: "Spring 2026"
  },
  {
    id: "davis-2025",
    piLastName: "Davis",
    piFirstName: "Jamaine",
    email: "jamaine.davis@belmont.edu",
    title: "Associate Professor",
    degree: "PhD",
    department: "FCS",
    researchFocus: "Basic science; Neurology; Radiation Oncology",
    keywords: "structural biology, mechanism of disease, lipid transport, DNA damage and repair",
    programDescription: "Decoding the biology of aging. Studying how gene variants reshape protein structures, disrupt normal function, and push cells toward disease (Cancer, Alzheimer's).",
    projectOverview: "Determining the structural basis for drug inhibition for enzymes.",
    studentCount: "2",
    timeframe: ["Summer Research Elective"],
    startTerm: "Summer 2026"
  },
  {
    id: "hendron-2025",
    piLastName: "Hendron",
    piFirstName: "Crystal",
    email: "crystal.hendron@belmont.edu",
    title: "Medical Education Educator",
    degree: "Ed.D.",
    department: "Student Affairs and Belonging",
    researchFocus: "Educational research, Medical Education",
    keywords: "Master Adaptive Learner, Academic Coaching, Peer-peer learning support, metacognition, resilience",
    programDescription: "Best practices and concerns relating to academic support in medical and health professions schools.",
    projectOverview: "Peer-to-peer learning support - evaluation and efficacy of services provided by the PAL Program. Academic Coaching and the development of master adaptive learners. Evidence-based practices for advancing academic support.",
    studentCount: "5-10",
    timeframe: ["Academic Year (Ongoing)"],
    startTerm: "Spring 2026"
  },
  {
    id: "davis-2026-1",
    piLastName: "Davis",
    piFirstName: "Jamaine",
    email: "jamaine.davis@belmont.edu",
    title: "Associate Professor",
    degree: "PhD",
    department: "FCS",
    researchFocus: "Oncology, Membrane Biology, Biochemistry",
    keywords: "ABCA transporters, cancer survival, breast cancer, ovarian cancer, lung cancer, pancreatic cancer",
    programDescription: "How do ABCA family member expression levels predict survival across breast, ovarian, lung, and pancreatic cancers?",
    projectOverview: "ABCA Family Transporters in Cancer",
    studentCount: "1",
    timeframe: ["Summer Research Elective", "Academic Year (Ongoing)"],
    startTerm: "Summer 2026",
    applicationDate: "Apply by 1/30/2026"
  },
  {
    id: "davis-2026-2",
    piLastName: "Davis",
    piFirstName: "Jamaine",
    email: "jamaine.davis@belmont.edu",
    title: "Associate Professor",
    degree: "PhD",
    department: "FCS",
    researchFocus: "Oncology, Pharmacology, Drug Resistance",
    keywords: "ABC transporters, chemotherapy resistance, drug response, cancer therapy",
    programDescription: "Can ABC transporter expression profiles predict chemotherapy response and treatment resistance?",
    projectOverview: "ABC Transporters and Chemotherapy Resistance",
    studentCount: "1",
    timeframe: ["Summer Research Elective", "Academic Year (Ongoing)"],
    startTerm: "Summer 2026",
    applicationDate: "Apply by 1/30/2026"
  },
  {
    id: "davis-2026-3",
    piLastName: "Davis",
    piFirstName: "Jamaine",
    email: "jamaine.davis@belmont.edu",
    title: "Associate Professor",
    degree: "PhD",
    department: "FCS",
    researchFocus: "Oncology, Metabolism, Breast Cancer",
    keywords: "TNBC, lipid metabolism, hormone-positive breast cancer, gene expression, prognosis",
    programDescription: "Do lipid metabolism genes predict outcomes differently in TNBC vs hormone-positive breast cancer?",
    projectOverview: "Lipid Metabolism in Triple-Negative Breast Cancer",
    studentCount: "1",
    timeframe: ["Summer Research Elective", "Academic Year (Ongoing)"],
    startTerm: "Summer 2026",
    applicationDate: "Apply by 1/30/2026"
  },
  {
    id: "davis-2026-4",
    piLastName: "Davis",
    piFirstName: "Jamaine",
    email: "jamaine.davis@belmont.edu",
    title: "Associate Professor",
    degree: "PhD",
    department: "FCS",
    researchFocus: "Oncology, Genetics, Lipid Biology",
    keywords: "APOE, cancer survival, isoforms, lipid-rich cancers, biomarkers",
    programDescription: "Does APOE expression and isoform status influence survival in lipid-rich cancers?",
    projectOverview: "APOE Expression in Cancer Survival",
    studentCount: "1",
    timeframe: ["Summer Research Elective", "Academic Year (Ongoing)"],
    startTerm: "Summer 2026",
    applicationDate: "Apply by 1/30/2026"
  },
  {
    id: "davis-2026-5",
    piLastName: "Davis",
    piFirstName: "Jamaine",
    email: "jamaine.davis@belmont.edu",
    title: "Associate Professor",
    degree: "PhD",
    department: "FCS",
    researchFocus: "Neurobiology, Oncology, Genetics",
    keywords: "Alzheimer's disease, cancer, shared pathways, prognostic markers, risk genes",
    programDescription: "Do AD-associated genes show prognostic value in cancers, suggesting shared pathways?",
    projectOverview: "Alzheimer's Risk Genes in Cancer",
    studentCount: "1",
    timeframe: ["Summer Research Elective", "Academic Year (Ongoing)"],
    startTerm: "Summer 2026",
    applicationDate: "Apply by 1/30/2026"
  },
  {
    id: "davis-2026-6",
    piLastName: "Davis",
    piFirstName: "Jamaine",
    email: "jamaine.davis@belmont.edu",
    title: "Associate Professor",
    degree: "PhD",
    department: "FCS",
    researchFocus: "Immunology, Oncology, Cell Biology",
    keywords: "Phagocytosis, tumor immunity, immune surveillance, cancer survival",
    programDescription: "Do genes regulating phagocytosis predict survival through tumor immune surveillance effects?",
    projectOverview: "Phagocytosis Genes in Tumor Immunity",
    studentCount: "1",
    timeframe: ["Summer Research Elective", "Academic Year (Ongoing)"],
    startTerm: "Summer 2026",
    applicationDate: "Apply by 1/30/2026"
  },
  {
    id: "davis-2026-7",
    piLastName: "Davis",
    piFirstName: "Jamaine",
    email: "jamaine.davis@belmont.edu",
    title: "Associate Professor",
    degree: "PhD",
    department: "FCS",
    researchFocus: "Cardiology, Metabolism, Genetics",
    keywords: "Mitochondria, heart failure, gene expression, metabolic genes, cardiovascular disease",
    programDescription: "Can mitochondrial and metabolic gene expression predict heart failure outcomes?",
    projectOverview: "Mitochondrial Genes in Cardiovascular Disease",
    studentCount: "1",
    timeframe: ["Summer Research Elective", "Academic Year (Ongoing)"],
    startTerm: "Summer 2026",
    applicationDate: "Apply by 1/30/2026"
  },
  {
    id: "davis-2026-8",
    piLastName: "Davis",
    piFirstName: "Jamaine",
    email: "jamaine.davis@belmont.edu",
    title: "Associate Professor",
    degree: "PhD",
    department: "FCS",
    researchFocus: "Oncology, Rare Diseases, Genetics",
    keywords: "Rare diseases, cancer biomarkers, gene expression",
    programDescription: "Do genes causing rare diseases show altered expression in cancers that could serve as biomarkers?",
    projectOverview: "Rare Disease Genes as Cancer Biomarkers",
    studentCount: "1",
    timeframe: ["Summer Research Elective", "Academic Year (Ongoing)"],
    startTerm: "Summer 2026",
    applicationDate: "Apply by 1/30/2026"
  },
  {
    id: "davis-2026-9",
    piLastName: "Davis",
    piFirstName: "Jamaine",
    email: "jamaine.davis@belmont.edu",
    title: "Associate Professor",
    degree: "PhD",
    department: "FCS",
    researchFocus: "Health Disparities, Genetics, Oncology",
    keywords: "Health disparities, ancestry, cancer outcomes, population genetics",
    programDescription: "Do genes with population-specific variants show expression patterns that correlate with outcome disparities?",
    projectOverview: "Ancestry-Specific Variants and Cancer Disparities",
    studentCount: "1",
    timeframe: ["Summer Research Elective", "Academic Year (Ongoing)"],
    startTerm: "Summer 2026",
    applicationDate: "Apply by 1/30/2026"
  },
  {
    id: "davis-2026-10",
    piLastName: "Davis",
    piFirstName: "Jamaine",
    email: "jamaine.davis@belmont.edu",
    title: "Associate Professor",
    degree: "PhD",
    department: "FCS",
    researchFocus: "Cell Biology, Oncology",
    keywords: "Lysosomes, autophagy, cancer progression, gene regulation",
    programDescription: "Do genes regulating lysosomal function predict outcomes in cancers with altered autophagy?",
    projectOverview: "Lysosomal Genes in Cancer Progression",
    studentCount: "1",
    timeframe: ["Summer Research Elective", "Academic Year (Ongoing)"],
    startTerm: "Summer 2026",
    applicationDate: "Apply by 1/30/2026"
  },
  {
    id: "davis-2026-11",
    piLastName: "Davis",
    piFirstName: "Jamaine",
    email: "jamaine.davis@belmont.edu",
    title: "Associate Professor",
    degree: "PhD",
    department: "FCS",
    researchFocus: "Systems Biology, Oncology, Bioinformatics",
    keywords: "Network biology, hub genes, protein-protein interaction, cancer prognosis",
    programDescription: "Do protein-protein interaction network hub genes show stronger prognostic value than peripheral genes?",
    projectOverview: "Network Hub Genes in Cancer",
    studentCount: "1",
    timeframe: ["Summer Research Elective", "Academic Year (Ongoing)"],
    startTerm: "Summer 2026",
    applicationDate: "Apply by 1/30/2026"
  },
  {
    id: "davis-2026-12",
    piLastName: "Davis",
    piFirstName: "Jamaine",
    email: "jamaine.davis@belmont.edu",
    title: "Associate Professor",
    degree: "PhD",
    department: "FCS",
    researchFocus: "Genetics, Oncology, Population Health",
    keywords: "Structural variants, population genetics, cancer outcomes, gene expression",
    programDescription: "Do genes with population-enriched structural variants show expression patterns influencing cancer outcomes?",
    projectOverview: "Structural Variants in Population-Specific Cancers",
    studentCount: "1",
    timeframe: ["Summer Research Elective", "Academic Year (Ongoing)"],
    startTerm: "Summer 2026",
    applicationDate: "Apply by 1/30/2026"
  }
]