import { ResearchOpportunity } from './types';

// Data parsed directly from the CSV provided in the prompt
export const RESEARCH_DATA: ResearchOpportunity[] = [
  {
    id: "kornu-2025",
    piLastName: "Kornu",
    piFirstName: "Kimbell",
    email: "kimbell.kornu@belmont.edu",
    title: "Professor (or Clinical Professor)",
    degree: "MD/PhD",
    department: "Foundational and Clinical Sciences",
    researchFocus: "Bioethics, Palliative Care, Clinical Ethics",
    keywords: "Religion, Theology, Bioethics, End of Life Care, Philosophy",
    programDescription: "I investigate philosophical, social, theological, and historical determinants that shape the practice of modern medicine, engaging in questions of mortality, technology, religion, spirituality, ways of knowing, philosophical anthropology, and clinical ethics.",
    projectOverview: "(1) Investigating the nature of AI as a mirror of how we conceptualize human intelligence and how that affects our understanding of what it means to be human both inside and outside of medicine. (2) Investigating principles from philosophy, theology, history, and the visual arts to consider the proper way to \"see\" a patient as a whole person.",
    studentCount: "10",
    timeframe: ["Summer Research Elective", "Academic Year (Ongoing)"],
    startTerm: ""
  },
  {
    id: "lowe-2025",
    piLastName: "Lowe",
    piFirstName: "Robert",
    email: "lowerw@toa.com",
    title: "MD TOA community faculty",
    degree: "MD",
    department: "Orthopedic",
    researchFocus: "Clinical research, Orthopaedic Surgery",
    keywords: "Spine, Clinical outcome research and possible cell biology",
    programDescription: "New faculty. Foster their own leaning style.",
    projectOverview: "Review of spine surgery outcomes. Help review and collect data.",
    studentCount: "1-2",
    timeframe: ["Summer Research Elective", "Academic Year (Ongoing)"],
    startTerm: ""
  },
  {
    id: "whitworth-2025",
    piLastName: "Whitworth",
    piFirstName: "Pat",
    email: "pat.whitworth@belmont.edu",
    title: "Assistant Professor",
    degree: "MD",
    department: "Clinical and/or Educational Research",
    researchFocus: "Basic science; Diagnostic Radiology; Interventional Radiology",
    keywords: "Radiology, Diagnostic Radiology, Interventional Radiology, AI, Artificial Intelligence",
    programDescription: "Current projects include radiology case reports, classic imaging signs, literature reviews, and research in the scholarship of teaching and learning including curriculum development.",
    projectOverview: "AMSER Case of the Month submissions; Classics in Abdominal Radiology (peer-reviewed); Literature reviews; Scholarship of teaching and learning (Radiology/POCUS curriculum development).",
    studentCount: "3",
    timeframe: ["Summer Research Elective", "Academic Year (Ongoing)"],
    startTerm: "Spring 2026"
  },
  {
    id: "ryan-b-1",
    piLastName: "Ryan",
    piFirstName: "Benjamin",
    email: "ben.ryan@belmont.edu",
    title: "Professor",
    degree: "PhD",
    department: "Health Systems Science",
    researchFocus: "Public health, Family Medicine",
    keywords: "Public health; environmental health science; disaster risk reduction; sanitation; community resilience; systems thinking; policy",
    programDescription: "I prioritize collaborative learning, real-world application, and interdisciplinary engagement. My mentoring style is supportive, adaptive, and goal-oriented.",
    projectOverview: "High tech/low tech medicine equity; The forgotten field of sanitation in medical curriculum; The dimensions of physician neutrality in conflict; Managing vaccination reluctance; Disaster detection/alerts; Disaster resilience standards.",
    studentCount: "10",
    timeframe: ["Academic Year (Ongoing)"],
    startTerm: "Spring 2026"
  },
  {
    id: "ryan-b-2",
    piLastName: "Ryan",
    piFirstName: "Benjamin",
    email: "ben.ryan@belmont.edu",
    title: "Professor",
    degree: "PhD",
    department: "Health Systems Science",
    researchFocus: "Public health, Diagnostic Radiology; Family Medicine; OBGYN",
    keywords: "C-section; ultrasound; pre-natal; Burundi",
    programDescription: "Focus on global health and humanitarian service leadership.",
    projectOverview: "Zigama-Mama: Evaluating benefit of free ultrasounds to pregnant women with C-section history in Burundi; Comparison of complication rates between urgent and scheduled repeat C-sections in Burundi; Heat wave preparedness in Turkey hospitals.",
    studentCount: "4",
    timeframe: ["Academic Year (Ongoing)"],
    startTerm: "Fall 2025"
  },
  {
    id: "thurman-2025",
    piLastName: "Thurman",
    piFirstName: "Kendall",
    email: "kendall.thurman@belmont.edu",
    title: "Assistant Professor",
    degree: "DO",
    department: "Foundational and Clinical Sciences",
    researchFocus: "Clinical research, Emergency Medicine; Family Medicine",
    keywords: "Doctor-Patient communication",
    programDescription: "How faculty perspective on students affects student mindset.",
    projectOverview: "A study on how faculty perspective on students affects student mindset. Does the outlook on students (deficit or asset-based) affect students' growth mindset? Surveys will be provided to faculty.",
    studentCount: "2-4",
    timeframe: ["Academic Year (Ongoing)"],
    startTerm: "Spring 2026"
  },
  {
    id: "davis-2025",
    piLastName: "Davis",
    piFirstName: "Jamaine",
    email: "jamaine.davis@belmont.edu",
    title: "Associate Professor",
    degree: "PhD",
    department: "FCS",
    researchFocus: "Basic science; Neurology; Radiation Oncology",
    keywords: "structural biology, mechanism of disease, lipid transport, DNA damage and repair",
    programDescription: "Decoding the biology of aging. Studying how gene variants reshape protein structures, disrupt normal function, and push cells toward disease (Cancer, Alzheimer's).",
    projectOverview: "Determining the structural basis for drug inhibition for enzymes.",
    studentCount: "2",
    timeframe: ["Summer Research Elective"],
    startTerm: "Summer 2026"
  },
  {
    id: "hendron-2025",
    piLastName: "Hendron",
    piFirstName: "Crystal",
    email: "crystal.hendron@belmont.edu",
    title: "Medical Education Educator",
    degree: "Ed.D.",
    department: "Student Affairs and Belonging",
    researchFocus: "Educational research, Medical Education",
    keywords: "Master Adaptive Learner, Academic Coaching, Peer-peer learning support, metacognition, resilience",
    programDescription: "Best practices and concerns relating to academic support in medical and health professions schools.",
    projectOverview: "Peer-to-peer learning support - evaluation and efficacy of services provided by the PAL Program. Academic Coaching and the development of master adaptive learners. Evidence-based practices for advancing academic support.",
    studentCount: "5-10",
    timeframe: ["Academic Year (Ongoing)"],
    startTerm: "Spring 2026"
  }
];
